name: KitBattleAbilities
author: CubicMinerSteve
version: 1.0
api-version: 1.13
main: me.cubicminer.kbabilities.KitBattleAbilities
depend:
  - KitBattle
softdepend:
  - AdvancedEnchantments
  - CrackShot
  - HolographicDisplays
  - MVdWPlaceholderAPI
  - PlaceholderAPI
  - TitleManager
  - Vault