name: KitBattleAbilities
author: CubicMinerSteve
version: 1.2.1
api-version: 1.13
main: code.cubicminer.kbabilities.KitBattleAbilities
depend:
  - KitBattle
commands:
  kbareload:
    discription: Reload Config
    usage: /command